# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh
source $ZSH/oh-my-zsh.sh

# zsh autoenv
source ~/dotfiles/lib/zsh-autoenv/autoenv.zsh
AUTOENV_FILE_ENTER='.env'
AUTOENV_FILE_LEAVE='.env-leave'

# export UPDATE_ZSH_DAYS=30
DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to enable command auto-correction.
plugins=(compleat autojump)

# for autojump
[[ -s $(brew --prefix)/etc/profile.d/autojump.sh ]] && . $(brew --prefix)/etc/profile.d/autojump.sh

# Settings
COMPLETION_WAITING_DOTS=true

# Ignore _blah function completions
zstyle ':completion:*:functions' ignored-patterns '_*'

source ~/.profile

CASE_SENSITIVE="false"

# Quick return to last suspended process
fancy-ctrl-z () {
  if [[ $#BUFFER -eq 0 ]]; then
    BUFFER="fg"
    zle accept-line
  else
    zle push-input
    zle clear-screen
  fi
}
zle -N fancy-ctrl-z
bindkey '^Z' fancy-ctrl-z

# Needed for easy colours.
autoload -U colors && colors

# function git_prompt_info() {
#     ref=$(git symbolic-ref HEAD 2> /dev/null) || return
#     echo "$ZSH_THEME_GIT_PROMPT_PREFIX${ref#refs/heads/}$ZSH_THEME_GIT_PROMPT_SUFFIX"
# }

# ZSH_THEME_GIT_PROMPT_DIRTY="%{$fg[yellow]%}✗%{$reset_color%}"
# ZSH_THEME_GIT_PROMPT_PREFIX="["
# ZSH_THEME_GIT_PROMPT_SUFFIX="] - "

# # these are used to indicate on the right side of the prompt
# ZSH_THEME_GIT_PROMPT_DIRTY="%{$fg[yellow]%}✗%{$fg[$HCOLOR]%}"
# PROMPT="%{$fg[cyan]%}\$(basename "\$(pwd)") > %{$reset_color%}"
# RPROMPT="%{$fg[cyan]%}\$(git_prompt_info)%~%{$reset_color%}"

function _update_ps1()
{
    export PROMPT="$(~/dotfiles/powerline-zsh.py -m konsole --cwd-only $?)"
    export RPROMPT="$(~/dotfiles/powerline-zsh.py -m konsole --cwd-only -r $?)"
}
precmd()
{
    _update_ps1
}

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Don't glob, bower will do the globbing.
alias bower='noglob bower'

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
